version: '3.9'

services:
  predictor-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: predictor_app
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
